class DummyData {
  static final loginSuccess = const {
    'status': 'success',
    'message': "Sukses",
    'results': {
      'company_name': "Demo",
      'company_id': "demo1",
      'company_join': "2026-08-30",
    },
  };

  static final loginFailed = const {};

  Map<String, dynamic> company = const {
    'company_name': "Demo",
    'company_id': "demo1",
    'company_join': "2026-08-30",
  };

  static final project = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "project_name": "Ringkas POS Mobile",
        "project_id": "PRJ001",
        "workspace_id": "WS001",
        "project_type": "Mobile App",
        "project_status": "On Progress",
        "project_created_by": "Oky",
        "project_created_id": "USR001",
        "project_total_contribut": 5,
        "project_start": "2026-05-01",
        "project_end": "2026-06-15",
      },
      {
        "project_name": "Ringkas Task",
        "project_id": "PRJ002",
        "workspace_id": "WS001",
        "project_type": "Flutter App",
        "project_status": "On Progress",
        "project_created_by": "Oky",
        "project_created_id": "USR001",
        "project_total_contribut": 8,
        "project_start": "2026-06-01",
        "project_end": "2026-09-01",
      },
      {
        "project_name": "Inventory Management System",
        "project_id": "PRJ003",
        "workspace_id": "WS002",
        "project_type": "Web App",
        "project_status": "Completed",
        "project_created_by": "Budi",
        "project_created_id": "USR002",
        "project_total_contribut": 6,
        "project_start": "2026-01-10",
        "project_end": "2026-03-25",
      },
      {
        "project_name": "CRM Dashboard",
        "project_id": "PRJ004",
        "workspace_id": "WS002",
        "project_type": "Admin Panel",
        "project_status": "On Progress",
        "project_created_by": "Ahmad",
        "project_created_id": "USR003",
        "project_total_contribut": 4,
        "project_start": "2026-04-01",
        "project_end": "2026-07-20",
      },
      {
        "project_name": "Customer Loyalty App",
        "project_id": "PRJ005",
        "workspace_id": "WS002",
        "project_type": "Mobile App",
        "project_status": "Pending",
        "project_created_by": "Sinta",
        "project_created_id": "USR004",
        "project_total_contribut": 3,
        "project_start": "2026-07-01",
        "project_end": "2026-10-01",
      },
      {
        "project_name": "Warehouse Monitoring",
        "project_id": "PRJ006",
        "workspace_id": "WS002",
        "project_type": "Desktop App",
        "project_status": "On Progress",
        "project_created_by": "Rizky",
        "project_created_id": "USR005",
        "project_total_contribut": 7,
        "project_start": "2026-03-10",
        "project_end": "2026-08-30",
      },
      {
        "project_name": "Finance Tracker",
        "project_id": "PRJ007",
        "workspace_id": "WS003",
        "project_type": "Desktop App",
        "project_status": "Cancelled",
        "project_created_by": "Dewi",
        "project_created_id": "USR006",
        "project_total_contribut": 2,
        "project_start": "2026-02-05",
        "project_end": "2026-05-30",
      },
      {
        "project_name": "Delivery Management",
        "project_id": "PRJ008",
        "workspace_id": "WS002",
        "project_type": "Web App",
        "project_status": "On Progress",
        "project_created_by": "Yoga",
        "project_created_id": "USR007",
        "project_total_contribut": 10,
        "project_start": "2026-04-20",
        "project_end": "2026-09-10",
      },
      {
        "project_name": "HR Information System",
        "project_id": "PRJ009",
        "workspace_id": "WS002",
        "project_type": "Web App",
        "project_status": "Review",
        "project_created_by": "Nadia",
        "project_created_id": "USR008",
        "project_total_contribut": 5,
        "project_start": "2026-03-15",
        "project_end": "2026-06-30",
      },
      {
        "project_name": "E-Commerce Dashboard",
        "project_id": "PRJ010",
        "workspace_id": "WS002",
        "project_type": "Admin Panel",
        "project_status": "On Progress",
        "project_created_by": "Citra",
        "project_created_id": "USR009",
        "project_total_contribut": 6,
        "project_start": "2026-04-12",
        "project_end": "2026-08-01",
      },
      {
        "project_name": "Booking Reservation System",
        "project_id": "PRJ011",
        "workspace_id": "WS003",
        "project_type": "Web App",
        "project_status": "Todo",
        "project_created_by": "Fajar",
        "project_created_id": "USR010",
        "project_total_contribut": 4,
        "project_start": "2026-08-01",
        "project_end": "2026-11-01",
      },
      {
        "project_name": "Analytics Reporting",
        "project_id": "PRJ012",
        "workspace_id": "WS003",
        "project_type": "Backend Service",
        "project_status": "On Progress",
        "project_created_by": "Lukman",
        "project_created_id": "USR011",
        "project_total_contribut": 5,
        "project_start": "2026-05-15",
        "project_end": "2026-08-15",
      },
    ],
  };

  static final user = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "USR001",
        "name": "Oky",
        "email": "oky@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR002",
        "name": "Ahmad Fauzi",
        "email": "ahmad@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR003",
        "name": "Budi Santoso",
        "email": "budi@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR004",
        "name": "Citra Dewi",
        "email": "citra@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR005",
        "name": "Rizky Pratama",
        "email": "rizky@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR006",
        "name": "Dewi Lestari",
        "email": "dewi@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR007",
        "name": "Yoga Saputra",
        "email": "yoga@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR008",
        "name": "Nadia Putri",
        "email": "nadia@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR009",
        "name": "Fajar Ramadhan",
        "email": "fajar@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR010",
        "name": "Lukman Hakim",
        "email": "lukman@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR011",
        "name": "Anisa",
        "email": "anisa@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR012",
        "name": "Kevin",
        "email": "kevin@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR013",
        "name": "Putra",
        "email": "putra@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR014",
        "name": "Sarah",
        "email": "sarah@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "id": "USR015",
        "name": "Farhan",
        "email": "farhan@ringkas.dev",
        "photo_url": "",
        "created_at": "2026-06-01T08:00:00Z",
        "company_id": "demo1",
      },
    ],
  };

  static final projectMember = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {"project_id": "PRJ001", "user_id": "USR001", "role": "Project Manager"},
      {
        "project_id": "PRJ001",
        "user_id": "USR002",
        "role": "Flutter Developer",
      },
      {
        "project_id": "PRJ001",
        "user_id": "USR003",
        "role": "Backend Developer",
      },
      {"project_id": "PRJ001", "user_id": "USR004", "role": "UI UX Designer"},
      {"project_id": "PRJ001", "user_id": "USR012", "role": "QA Engineer"},
      {"project_id": "PRJ002", "user_id": "USR001", "role": "Product Owner"},
      {
        "project_id": "PRJ002",
        "user_id": "USR002",
        "role": "Flutter Developer",
      },
      {
        "project_id": "PRJ002",
        "user_id": "USR003",
        "role": "Backend Developer",
      },
      {"project_id": "PRJ002", "user_id": "USR004", "role": "UI UX Designer"},
      {"project_id": "PRJ002", "user_id": "USR011", "role": "QA Engineer"},
      {"project_id": "PRJ003", "user_id": "USR005", "role": "Project Manager"},
      {
        "project_id": "PRJ003",
        "user_id": "USR006",
        "role": "Frontend Developer",
      },
      {
        "project_id": "PRJ003",
        "user_id": "USR007",
        "role": "Backend Developer",
      },
    ],
  };

  static final task = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "TASK001",
        "project_id": "PRJ002",
        "title": "Setup Clean Architecture",
        "description": "Create base folder structure and dependencies",
        "status": "done",
        "priority": "high",
        "story_point": 5,
        "reporter_id": "USR001",
        "assignee_id": "USR002",
        "label_ids": ["LBL002", "LBL006"],
        "start_date": "2026-06-01",
        "due_date": "2026-06-03",
        "created_at": "2026-06-01T08:00:00Z",
        "updated_at": "2026-06-03T16:30:00Z",
      },
      {
        "id": "TASK002",
        "project_id": "PRJ002",
        "title": "Setup Firebase Project",
        "description": "Configure Firebase Auth and Firestore",
        "status": "done",
        "priority": "high",
        "story_point": 3,
        "reporter_id": "USR001",
        "assignee_id": "USR003",
        "label_ids": ["LBL002", "LBL005"],
        "start_date": "2026-06-01",
        "due_date": "2026-06-02",
        "created_at": "2026-06-01T09:00:00Z",
        "updated_at": "2026-06-02T17:45:00Z",
      },
      {
        "id": "TASK003",
        "project_id": "PRJ002",
        "title": "Create Login Screen",
        "description": "Build login UI page",
        "status": "done",
        "priority": "medium",
        "story_point": 3,
        "reporter_id": "USR001",
        "assignee_id": "USR004",
        "label_ids": ["LBL001", "LBL003"],
        "start_date": "2026-06-02",
        "due_date": "2026-06-04",
        "created_at": "2026-06-02T08:00:00Z",
        "updated_at": "2026-06-04T15:20:00Z",
      },
      {
        "id": "TASK004",
        "project_id": "PRJ002",
        "title": "Implement Authentication",
        "description": "Connect login screen to Firebase Auth",
        "status": "review",
        "priority": "high",
        "story_point": 8,
        "reporter_id": "USR001",
        "assignee_id": "USR002",
        "label_ids": ["LBL002", "LBL005"],
        "start_date": "2026-06-03",
        "due_date": "2026-06-08",
        "created_at": "2026-06-03T08:00:00Z",
        "updated_at": "2026-06-05T17:00:00Z",
      },
      {
        "id": "TASK005",
        "project_id": "PRJ002",
        "title": "Create Workspace Module",
        "description": "Create CRUD Workspace",
        "status": "in_progress",
        "priority": "high",
        "story_point": 13,
        "reporter_id": "USR001",
        "assignee_id": "USR003",
        "label_ids": ["LBL005"],
        "start_date": "2026-06-05",
        "due_date": "2026-06-15",
        "created_at": "2026-06-05T09:00:00Z",
        "updated_at": "2026-06-05T10:30:00Z",
      },
      {
        "id": "TASK006",
        "project_id": "PRJ002",
        "title": "Create Project Module",
        "description": "Create CRUD Project",
        "status": "in_progress",
        "priority": "high",
        "story_point": 13,
        "reporter_id": "USR001",
        "assignee_id": "USR002",
        "label_ids": ["LBL005"],
        "start_date": "2026-06-05",
        "due_date": "2026-06-15",
        "created_at": "2026-06-05T09:10:00Z",
        "updated_at": "2026-06-06T08:15:00Z",
      },
      {
        "id": "TASK007",
        "project_id": "PRJ002",
        "title": "Create Task Module",
        "description": "Create CRUD Task",
        "status": "todo",
        "priority": "highest",
        "story_point": 21,
        "reporter_id": "USR001",
        "assignee_id": "USR003",
        "label_ids": ["LBL005"],
        "start_date": "2026-06-10",
        "due_date": "2026-06-25",
        "created_at": "2026-06-06T08:00:00Z",
        "updated_at": "2026-06-06T08:00:00Z",
      },
      {
        "id": "TASK008",
        "project_id": "PRJ002",
        "title": "Kanban Board",
        "description": "Build drag and drop task board",
        "status": "todo",
        "priority": "high",
        "story_point": 13,
        "reporter_id": "USR001",
        "assignee_id": "USR002",
        "label_ids": ["LBL001", "LBL005"],
        "start_date": "2026-06-12",
        "due_date": "2026-06-25",
        "created_at": "2026-06-06T09:00:00Z",
        "updated_at": "2026-06-06T09:00:00Z",
      },
      {
        "id": "TASK009",
        "project_id": "PRJ002",
        "title": "Notification System",
        "description": "Realtime task notification",
        "status": "todo",
        "priority": "medium",
        "story_point": 8,
        "reporter_id": "USR001",
        "assignee_id": "USR011",
        "label_ids": ["LBL002", "LBL005", "LBL007"],
        "start_date": "2026-06-15",
        "due_date": "2026-06-30",
        "created_at": "2026-06-06T10:00:00Z",
        "updated_at": "2026-06-06T10:00:00Z",
      },
      {
        "id": "TASK010",
        "project_id": "PRJ001",
        "title": "Release v1.0",
        "description": "Production deployment",
        "status": "todo",
        "priority": "highest",
        "story_point": 5,
        "reporter_id": "USR001",
        "assignee_id": "USR001",
        "label_ids": ["LBL007"],
        "start_date": "2026-08-25",
        "due_date": "2026-09-01",
        "created_at": "2026-06-06T11:00:00Z",
        "updated_at": "2026-06-06T11:00:00Z",
      },
    ],
  };

  static final subTask = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "SUB001",
        "task_id": "TASK005",
        "title": "Create Workspace Entity",
        "is_done": true,
      },
      {
        "id": "SUB002",
        "task_id": "TASK005",
        "title": "Create Workspace Model",
        "is_done": true,
      },
      {
        "id": "SUB003",
        "task_id": "TASK005",
        "title": "Create Workspace Repository",
        "is_done": false,
      },
      {
        "id": "SUB004",
        "task_id": "TASK005",
        "title": "Create Workspace Bloc",
        "is_done": false,
      },
      {
        "id": "SUB005",
        "task_id": "TASK005",
        "title": "Workspace UI",
        "is_done": false,
      },
      {
        "id": "SUB006",
        "task_id": "TASK006",
        "title": "Project Entity",
        "is_done": true,
      },
      {
        "id": "SUB007",
        "task_id": "TASK006",
        "title": "Project Repository",
        "is_done": false,
      },
      {
        "id": "SUB008",
        "task_id": "TASK006",
        "title": "Project Screen",
        "is_done": false,
      },
    ],
  };

  static final label = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {"id": "LBL001", "name": "Frontend", "color": "#4CAF50"},
      {"id": "LBL002", "name": "Backend", "color": "#2196F3"},
      {"id": "LBL003", "name": "UI/UX", "color": "#FF9800"},
      {"id": "LBL004", "name": "Bug", "color": "#F44336"},
      {"id": "LBL005", "name": "Feature", "color": "#9C27B0"},
      {"id": "LBL006", "name": "Improvement", "color": "#795548"},
      {"id": "LBL007", "name": "Release", "color": "#009688"},
    ],
  };

  static final comment = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "COM001",
        "task_id": "TASK004",
        "user_id": "USR003",
        "content": "Firebase Auth already configured.",
        "created_at": "2026-06-05T08:00:00Z",
        "updated_at": "2026-06-05T08:00:00Z",
      },
      {
        "id": "COM002",
        "task_id": "TASK004",
        "user_id": "USR002",
        "content": "Need testing on Android 14.",
        "created_at": "2026-06-05T09:15:00Z",
        "updated_at": "2026-06-05T09:15:00Z",
      },
      {
        "id": "COM003",
        "task_id": "TASK005",
        "user_id": "USR001",
        "content": "Workspace hierarchy approved.",
        "created_at": "2026-06-06T10:00:00Z",
        "updated_at": "2026-06-06T10:05:00Z",
      },
      {
        "id": "COM004",
        "task_id": "TASK006",
        "user_id": "USR004",
        "content": "Project form design uploaded.",
        "created_at": "2026-06-06T11:00:00Z",
        "updated_at": "2026-06-06T11:00:00Z",
      },
      {
        "id": "COM005",
        "task_id": "TASK005",
        "user_id": "USR003",
        "content": "Repository implementation finished.",
        "created_at": "2026-06-06T12:00:00Z",
        "updated_at": "2026-06-06T12:20:00Z",
      },
      {
        "id": "COM006",
        "task_id": "TASK005",
        "user_id": "USR002",
        "content": "Need additional validation for workspace name.",
        "created_at": "2026-06-06T13:00:00Z",
        "updated_at": "2026-06-06T13:00:00Z",
      },
      {
        "id": "COM007",
        "task_id": "TASK006",
        "user_id": "USR001",
        "content": "Please follow clean architecture structure.",
        "created_at": "2026-06-06T14:00:00Z",
        "updated_at": "2026-06-06T14:00:00Z",
      },
      {
        "id": "COM008",
        "task_id": "TASK006",
        "user_id": "USR004",
        "content": "UI ready for implementation.",
        "created_at": "2026-06-06T15:00:00Z",
        "updated_at": "2026-06-06T15:45:00Z",
      },
      {
        "id": "COM009",
        "task_id": "TASK007",
        "user_id": "USR003",
        "content": "Starting database schema design.",
        "created_at": "2026-06-07T08:00:00Z",
        "updated_at": "2026-06-07T08:00:00Z",
      },
      {
        "id": "COM010",
        "task_id": "TASK007",
        "user_id": "USR011",
        "content": "Need discussion about task hierarchy.",
        "created_at": "2026-06-07T08:30:00Z",
        "updated_at": "2026-06-07T09:10:00Z",
      },
      {
        "id": "COM011",
        "task_id": "TASK008",
        "user_id": "USR002",
        "content": "Drag and drop package selected.",
        "created_at": "2026-06-07T09:00:00Z",
        "updated_at": "2026-06-07T09:00:00Z",
      },
      {
        "id": "COM012",
        "task_id": "TASK008",
        "user_id": "USR001",
        "content": "Looks good, continue implementation.",
        "created_at": "2026-06-07T10:00:00Z",
        "updated_at": "2026-06-07T10:00:00Z",
      },
      {
        "id": "COM013",
        "task_id": "TASK009",
        "user_id": "USR011",
        "content": "Realtime listener completed.",
        "created_at": "2026-06-08T08:00:00Z",
        "updated_at": "2026-06-08T08:25:00Z",
      },
      {
        "id": "COM014",
        "task_id": "TASK009",
        "user_id": "USR002",
        "content": "Need badge counter update.",
        "created_at": "2026-06-08T09:00:00Z",
        "updated_at": "2026-06-08T09:00:00Z",
      },
      {
        "id": "COM015",
        "task_id": "TASK010",
        "user_id": "USR001",
        "content": "Prepare release checklist.",
        "created_at": "2026-06-08T10:00:00Z",
        "updated_at": "2026-06-08T10:00:00Z",
      },
      {
        "id": "COM016",
        "task_id": "TASK004",
        "user_id": "USR004",
        "content": "Login page design updated.",
        "created_at": "2026-06-08T11:00:00Z",
        "updated_at": "2026-06-08T11:35:00Z",
      },
      {
        "id": "COM017",
        "task_id": "TASK004",
        "user_id": "USR002",
        "content": "Authentication flow passed testing.",
        "created_at": "2026-06-08T12:00:00Z",
        "updated_at": "2026-06-08T12:00:00Z",
      },
      {
        "id": "COM018",
        "task_id": "TASK005",
        "user_id": "USR001",
        "content": "Workspace module almost complete.",
        "created_at": "2026-06-08T13:00:00Z",
        "updated_at": "2026-06-08T13:15:00Z",
      },
      {
        "id": "COM019",
        "task_id": "TASK006",
        "user_id": "USR003",
        "content": "Firestore indexes created.",
        "created_at": "2026-06-08T14:00:00Z",
        "updated_at": "2026-06-08T14:00:00Z",
      },
      {
        "id": "COM020",
        "task_id": "TASK007",
        "user_id": "USR011",
        "content": "Need QA review before merge.",
        "created_at": "2026-06-08T15:00:00Z",
        "updated_at": "2026-06-08T15:40:00Z",
      },
    ],
  };

  static final attachment = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "ATT001",
        "task_id": "TASK004",
        "file_name": "auth-flow.png",
        "file_url": "https://dummy.com/auth-flow.png",
        "file_size": 512000,
        "uploaded_by": "USR004",
        "uploaded_at": "2026-05-02T09:15:00Z",
      },
      {
        "id": "ATT002",
        "task_id": "TASK005",
        "file_name": "workspace-diagram.drawio",
        "file_url": "https://dummy.com/workspace-diagram.drawio",
        "file_size": 1048576,
        "uploaded_by": "USR001",
        "uploaded_at": "2026-05-03T10:30:00Z",
      },
      {
        "id": "ATT003",
        "task_id": "TASK006",
        "file_name": "project-ui.fig",
        "file_url": "https://dummy.com/project-ui.fig",
        "file_size": 3048576,
        "uploaded_by": "USR004",
        "uploaded_at": "2026-05-04T08:45:00Z",
      },
      {
        "id": "ATT004",
        "task_id": "TASK007",
        "file_name": "task-schema.pdf",
        "file_url": "https://dummy.com/task-schema.pdf",
        "file_size": 842000,
        "uploaded_by": "USR003",
        "uploaded_at": "2026-05-05T14:20:00Z",
      },
      {
        "id": "ATT005",
        "task_id": "TASK007",
        "file_name": "erd-v2.png",
        "file_url": "https://dummy.com/erd-v2.png",
        "file_size": 1200000,
        "uploaded_by": "USR003",
        "uploaded_at": "2026-05-05T15:10:00Z",
      },
      {
        "id": "ATT006",
        "task_id": "TASK008",
        "file_name": "kanban-reference.png",
        "file_url": "https://dummy.com/kanban-reference.png",
        "file_size": 650000,
        "uploaded_by": "USR002",
        "uploaded_at": "2026-05-06T11:00:00Z",
      },
      {
        "id": "ATT007",
        "task_id": "TASK008",
        "file_name": "board-flow.pdf",
        "file_url": "https://dummy.com/board-flow.pdf",
        "file_size": 900000,
        "uploaded_by": "USR001",
        "uploaded_at": "2026-05-06T13:40:00Z",
      },
      {
        "id": "ATT008",
        "task_id": "TASK009",
        "file_name": "notification-sequence.png",
        "file_url": "https://dummy.com/notification-sequence.png",
        "file_size": 1100000,
        "uploaded_by": "USR011",
        "uploaded_at": "2026-05-07T09:25:00Z",
      },
      {
        "id": "ATT009",
        "task_id": "TASK009",
        "file_name": "firebase-trigger.md",
        "file_url": "https://dummy.com/firebase-trigger.md",
        "file_size": 12000,
        "uploaded_by": "USR011",
        "uploaded_at": "2026-05-07T10:05:00Z",
      },
      {
        "id": "ATT010",
        "task_id": "TASK010",
        "file_name": "release-checklist.xlsx",
        "file_url": "https://dummy.com/release-checklist.xlsx",
        "file_size": 560000,
        "uploaded_by": "USR001",
        "uploaded_at": "2026-05-08T16:30:00Z",
      },
      {
        "id": "ATT011",
        "task_id": "TASK004",
        "file_name": "login-screen-v2.png",
        "file_url": "https://dummy.com/login-screen-v2.png",
        "file_size": 430000,
        "uploaded_by": "USR004",
        "uploaded_at": "2026-05-09T08:10:00Z",
      },
      {
        "id": "ATT012",
        "task_id": "TASK005",
        "file_name": "workspace-api.docx",
        "file_url": "https://dummy.com/workspace-api.docx",
        "file_size": 250000,
        "uploaded_by": "USR003",
        "uploaded_at": "2026-05-09T14:55:00Z",
      },
      {
        "id": "ATT013",
        "task_id": "TASK006",
        "file_name": "project-module-flow.png",
        "file_url": "https://dummy.com/project-module-flow.png",
        "file_size": 800000,
        "uploaded_by": "USR001",
        "uploaded_at": "2026-05-10T09:40:00Z",
      },
      {
        "id": "ATT014",
        "task_id": "TASK008",
        "file_name": "kanban-ui.fig",
        "file_url": "https://dummy.com/kanban-ui.fig",
        "file_size": 2500000,
        "uploaded_by": "USR004",
        "uploaded_at": "2026-05-10T15:20:00Z",
      },
      {
        "id": "ATT015",
        "task_id": "TASK009",
        "file_name": "notification-mockup.png",
        "file_url": "https://dummy.com/notification-mockup.png",
        "file_size": 670000,
        "uploaded_by": "USR004",
        "uploaded_at": "2026-05-11T11:35:00Z",
      },
    ],
  };

  static final activity = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "ACT001",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "user_id": "USR001",
        "action": "CREATE_TASK",
        "old_value": "",
        "new_value": "TASK004",
        "created_at": "2026-06-03T08:00:00Z",
      },
      {
        "id": "ACT002",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "user_id": "USR001",
        "action": "ASSIGN_TASK",
        "old_value": "",
        "new_value": "USR002",
        "created_at": "2026-06-03T08:05:00Z",
      },
      {
        "id": "ACT003",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "user_id": "USR002",
        "action": "CHANGE_STATUS",
        "old_value": "todo",
        "new_value": "in_progress",
        "created_at": "2026-06-04T09:00:00Z",
      },
      {
        "id": "ACT004",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "user_id": "USR002",
        "action": "CHANGE_PRIORITY",
        "old_value": "medium",
        "new_value": "high",
        "created_at": "2026-06-04T09:05:00Z",
      },
      {
        "id": "ACT005",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "user_id": "USR004",
        "action": "ADD_ATTACHMENT",
        "old_value": "",
        "new_value": "ATT011",
        "created_at": "2026-06-04T09:30:00Z",
      },
      {
        "id": "ACT006",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "user_id": "USR002",
        "action": "CHANGE_STATUS",
        "old_value": "in_progress",
        "new_value": "review",
        "created_at": "2026-05-17T00:00:00Z",
      },

      {
        "id": "ACT007",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "user_id": "USR001",
        "action": "CREATE_TASK",
        "old_value": "",
        "new_value": "TASK005",
        "created_at": "2026-06-05T08:00:00Z",
      },
      {
        "id": "ACT008",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "user_id": "USR001",
        "action": "ASSIGN_TASK",
        "old_value": "",
        "new_value": "USR003",
        "created_at": "2026-06-05T08:10:00Z",
      },
      {
        "id": "ACT009",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "user_id": "USR003",
        "action": "CHANGE_STATUS",
        "old_value": "todo",
        "new_value": "in_progress",
        "created_at": "2026-06-05T09:00:00Z",
      },
      {
        "id": "ACT010",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "user_id": "USR003",
        "action": "ADD_ATTACHMENT",
        "old_value": "",
        "new_value": "ATT012",
        "created_at": "2026-06-05T10:00:00Z",
      },
      {
        "id": "ACT011",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "user_id": "USR003",
        "action": "ADD_COMMENT",
        "old_value": "",
        "new_value": "COM018",
        "created_at": "2026-06-06T08:00:00Z",
      },
      {
        "id": "ACT012",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "user_id": "USR003",
        "action": "COMPLETE_SUBTASK",
        "old_value": "SUB003",
        "new_value": "done",
        "created_at": "2026-06-06T09:00:00Z",
      },

      {
        "id": "ACT013",
        "workspace_id": "WS001",
        "task_id": "TASK006",
        "user_id": "USR001",
        "action": "CREATE_TASK",
        "old_value": "",
        "new_value": "TASK006",
        "created_at": "2026-06-05T11:00:00Z",
      },
      {
        "id": "ACT014",
        "workspace_id": "WS001",
        "task_id": "TASK006",
        "user_id": "USR002",
        "action": "MOVE_TO_SPRINT",
        "old_value": "Backlog",
        "new_value": "Sprint 1",
        "created_at": "2026-06-05T12:00:00Z",
      },
      {
        "id": "ACT015",
        "workspace_id": "WS001",
        "task_id": "TASK006",
        "user_id": "USR003",
        "action": "ADD_LABEL",
        "old_value": "",
        "new_value": "LBL005",
        "created_at": "2026-06-05T13:00:00Z",
      },

      {
        "id": "ACT016",
        "workspace_id": "WS002",
        "task_id": "TASK007",
        "user_id": "USR001",
        "action": "CREATE_TASK",
        "old_value": "",
        "new_value": "TASK007",
        "created_at": "2026-06-06T08:00:00Z",
      },
      {
        "id": "ACT017",
        "workspace_id": "WS002",
        "task_id": "TASK007",
        "user_id": "USR003",
        "action": "ESTIMATE_STORY_POINT",
        "old_value": "0",
        "new_value": "21",
        "created_at": "2026-06-06T08:30:00Z",
      },
      {
        "id": "ACT018",
        "workspace_id": "WS002",
        "task_id": "TASK007",
        "user_id": "USR011",
        "action": "ADD_COMMENT",
        "old_value": "",
        "new_value": "COM020",
        "created_at": "2026-06-06T09:00:00Z",
      },

      {
        "id": "ACT019",
        "workspace_id": "WS002",
        "task_id": "TASK008",
        "user_id": "USR002",
        "action": "CREATE_BOARD",
        "old_value": "",
        "new_value": "Kanban",
        "created_at": "2026-06-07T08:00:00Z",
      },
      {
        "id": "ACT020",
        "workspace_id": "WS002",
        "task_id": "TASK008",
        "user_id": "USR002",
        "action": "ADD_ATTACHMENT",
        "old_value": "",
        "new_value": "ATT014",
        "created_at": "2026-06-07T08:30:00Z",
      },

      {
        "id": "ACT021",
        "workspace_id": "WS003",
        "task_id": "TASK009",
        "user_id": "USR011",
        "action": "CREATE_TASK",
        "old_value": "",
        "new_value": "TASK009",
        "created_at": "2026-06-08T08:00:00Z",
      },
      {
        "id": "ACT022",
        "workspace_id": "WS003",
        "task_id": "TASK009",
        "user_id": "USR011",
        "action": "ADD_ATTACHMENT",
        "old_value": "",
        "new_value": "ATT015",
        "created_at": "2026-06-08T08:15:00Z",
      },
      {
        "id": "ACT023",
        "workspace_id": "WS003",
        "task_id": "TASK009",
        "user_id": "USR011",
        "action": "CHANGE_STATUS",
        "old_value": "todo",
        "new_value": "in_progress",
        "created_at": "2026-06-08T09:00:00Z",
      },

      {
        "id": "ACT024",
        "workspace_id": "WS003",
        "task_id": "TASK010",
        "user_id": "USR001",
        "action": "CREATE_RELEASE",
        "old_value": "",
        "new_value": "v1.0.0",
        "created_at": "2026-06-08T10:00:00Z",
      },
      {
        "id": "ACT025",
        "workspace_id": "WS003",
        "task_id": "TASK010",
        "user_id": "USR001",
        "action": "SET_DUE_DATE",
        "old_value": "",
        "new_value": "2026-09-01",
        "created_at": "2026-06-08T10:05:00Z",
      },

      {
        "id": "ACT026",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "user_id": "USR002",
        "action": "LOG_WORK",
        "old_value": "0",
        "new_value": "4h",
        "created_at": "2026-06-08T11:00:00Z",
      },
      {
        "id": "ACT027",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "user_id": "USR003",
        "action": "LOG_WORK",
        "old_value": "0",
        "new_value": "6h",
        "created_at": "2026-06-08T11:30:00Z",
      },
      {
        "id": "ACT028",
        "workspace_id": "WS001",
        "task_id": "TASK006",
        "user_id": "USR002",
        "action": "LOG_WORK",
        "old_value": "0",
        "new_value": "5h",
        "created_at": "2026-06-08T12:00:00Z",
      },
      {
        "id": "ACT029",
        "workspace_id": "WS002",
        "task_id": "TASK007",
        "user_id": "USR003",
        "action": "LOG_WORK",
        "old_value": "0",
        "new_value": "7h",
        "created_at": "2026-06-08T12:30:00Z",
      },
      {
        "id": "ACT030",
        "workspace_id": "WS002",
        "task_id": "TASK008",
        "user_id": "USR002",
        "action": "LOG_WORK",
        "old_value": "0",
        "new_value": "3h",
        "created_at": "2026-06-08T13:00:00Z",
      },
    ],
  };

  static final workspace = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "workspace_id": "WS001",
        "workspace_name": "Ringkas Development",
        "workspace_description": "Internal product development",
        "workspace_owner_id": "USR001",
        "created_at": "2026-01-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "workspace_id": "WS002",
        "workspace_name": "PT Maju Bersama",
        "workspace_description": "Client workspace",
        "workspace_owner_id": "USR004",
        "created_at": "2026-02-01T08:00:00Z",
        "company_id": "demo1",
      },
      {
        "workspace_id": "WS003",
        "workspace_name": "Freelance Projects",
        "workspace_description": "Freelance client management",
        "workspace_owner_id": "USR001",
        "created_at": "2026-03-01T08:00:00Z",
        "company_id": "demo1",
      },
    ],
  };

  static final workspaceMember = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {"workspace_id": "WS001", "user_id": "USR001", "role": "Owner"},
      {"workspace_id": "WS001", "user_id": "USR002", "role": "Admin"},
      {"workspace_id": "WS001", "user_id": "USR003", "role": "Member"},
      {"workspace_id": "WS001", "user_id": "USR004", "role": "Member"},
      {"workspace_id": "WS001", "user_id": "USR011", "role": "Member"},
      {"workspace_id": "WS002", "user_id": "USR004", "role": "Owner"},
      {"workspace_id": "WS002", "user_id": "USR005", "role": "Admin"},
      {"workspace_id": "WS002", "user_id": "USR006", "role": "Member"},
      {"workspace_id": "WS003", "user_id": "USR001", "role": "Owner"},
      {"workspace_id": "WS003", "user_id": "USR007", "role": "Member"},
    ],
  };

  static final sprint = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "sprint_id": "SPR001",
        "project_id": "PRJ002",
        "sprint_name": "Sprint 1",
        "sprint_goal": "Authentication and Workspace Module",
        "start_date": "2026-06-01",
        "end_date": "2026-06-14",
        "is_active": false,
      },
      {
        "sprint_id": "SPR002",
        "project_id": "PRJ002",
        "sprint_name": "Sprint 2",
        "sprint_goal": "Project and Task Module",
        "start_date": "2026-06-15",
        "end_date": "2026-06-28",
        "is_active": true,
      },
      {
        "sprint_id": "SPR003",
        "project_id": "PRJ002",
        "sprint_name": "Sprint 3",
        "sprint_goal": "Kanban Board and Notification",
        "start_date": "2026-06-29",
        "end_date": "2026-07-12",
        "is_active": false,
      },
      {
        "sprint_id": "SPR004",
        "project_id": "PRJ002",
        "sprint_name": "Sprint 4",
        "sprint_goal": "Release Preparation",
        "start_date": "2026-07-13",
        "end_date": "2026-07-26",
        "is_active": false,
      },
    ],
  };

  static final notification = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "NTF001",
        "user_id": "USR002",
        "title": "Task Assigned",
        "body": "You have been assigned to TASK006",
        "is_read": false,
        "created_at": "2026-06-06T08:00:00Z",
      },
      {
        "id": "NTF002",
        "user_id": "USR003",
        "title": "Task Assigned",
        "body": "You have been assigned to TASK005",
        "is_read": true,
        "created_at": "2026-06-06T08:05:00Z",
      },
      {
        "id": "NTF003",
        "user_id": "USR004",
        "title": "Comment Mention",
        "body": "Oky mentioned you in TASK004",
        "is_read": false,
        "created_at": "2026-06-06T09:00:00Z",
      },
      {
        "id": "NTF004",
        "user_id": "USR011",
        "title": "Review Requested",
        "body": "Review requested for TASK007",
        "is_read": false,
        "created_at": "2026-06-06T10:00:00Z",
      },
      {
        "id": "NTF005",
        "user_id": "USR001",
        "title": "Sprint Started",
        "body": "Sprint 2 has started",
        "is_read": true,
        "created_at": "2026-06-15T08:00:00Z",
      },
      {
        "id": "NTF006",
        "user_id": "USR002",
        "title": "Task Status Updated",
        "body": "TASK004 moved to Review",
        "is_read": true,
        "created_at": "2026-06-08T13:00:00Z",
      },
      {
        "id": "NTF007",
        "user_id": "USR003",
        "title": "Attachment Added",
        "body": "New attachment added to TASK005",
        "is_read": false,
        "created_at": "2026-06-08T14:00:00Z",
      },
      {
        "id": "NTF008",
        "user_id": "USR004",
        "title": "Project Invitation",
        "body": "You were invited to PRJ002",
        "is_read": true,
        "created_at": "2026-06-01T08:00:00Z",
      },
    ],
  };

  static final taskHistory = const {
    'status': 'success',
    'message': "Sukses",
    'results': [
      {
        "id": "HIS001",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "field": "status",
        "old_value": "todo",
        "new_value": "in_progress",
        "changed_by": "USR002",
        "changed_at": "2026-06-04T09:00:00Z",
      },
      {
        "id": "HIS002",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "field": "priority",
        "old_value": "medium",
        "new_value": "high",
        "changed_by": "USR001",
        "changed_at": "2026-06-04T09:15:00Z",
      },
      {
        "id": "HIS003",
        "workspace_id": "WS001",
        "task_id": "TASK004",
        "field": "status",
        "old_value": "in_progress",
        "new_value": "review",
        "changed_by": "USR002",
        "changed_at": "2026-06-05T17:00:00Z",
      },
      {
        "id": "HIS004",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "field": "assigneeId",
        "old_value": "",
        "new_value": "USR003",
        "changed_by": "USR001",
        "changed_at": "2026-06-05T08:10:00Z",
      },
      {
        "id": "HIS005",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "field": "status",
        "old_value": "todo",
        "new_value": "in_progress",
        "changed_by": "USR003",
        "changed_at": "2026-06-05T09:00:00Z",
      },
      {
        "id": "HIS006",
        "workspace_id": "WS001",
        "task_id": "TASK005",
        "field": "storyPoint",
        "old_value": "8",
        "new_value": "13",
        "changed_by": "USR001",
        "changed_at": "2026-06-05T10:30:00Z",
      },
      {
        "id": "HIS007",
        "workspace_id": "WS001",
        "task_id": "TASK006",
        "field": "dueDate",
        "old_value": "2026-06-12",
        "new_value": "2026-06-15",
        "changed_by": "USR001",
        "changed_at": "2026-06-06T08:00:00Z",
      },
      {
        "id": "HIS008",
        "workspace_id": "WS001",
        "task_id": "TASK006",
        "field": "assigneeId",
        "old_value": "USR003",
        "new_value": "USR002",
        "changed_by": "USR001",
        "changed_at": "2026-06-06T08:15:00Z",
      },
      {
        "id": "HIS009",
        "workspace_id": "WS002",
        "task_id": "TASK007",
        "field": "status",
        "old_value": "todo",
        "new_value": "in_progress",
        "changed_by": "USR003",
        "changed_at": "2026-06-07T08:00:00Z",
      },
      {
        "id": "HIS010",
        "workspace_id": "WS002",
        "task_id": "TASK007",
        "field": "status",
        "old_value": "in_progress",
        "new_value": "review",
        "changed_by": "USR011",
        "changed_at": "2026-06-08T10:00:00Z",
      },
      {
        "id": "HIS011",
        "workspace_id": "WS002",
        "task_id": "TASK007",
        "field": "status",
        "old_value": "review",
        "new_value": "done",
        "changed_by": "USR011",
        "changed_at": "2026-06-09T16:00:00Z",
      },
      {
        "id": "HIS012",
        "workspace_id": "WS002",
        "task_id": "TASK008",
        "field": "priority",
        "old_value": "medium",
        "new_value": "highest",
        "changed_by": "USR001",
        "changed_at": "2026-06-10T09:00:00Z",
      },
      {
        "id": "HIS013",
        "workspace_id": "WS002",
        "task_id": "TASK008",
        "field": "dueDate",
        "old_value": "2026-06-20",
        "new_value": "2026-06-25",
        "changed_by": "USR001",
        "changed_at": "2026-06-10T09:10:00Z",
      },
      {
        "id": "HIS014",
        "workspace_id": "WS003",
        "task_id": "TASK009",
        "field": "assigneeId",
        "old_value": "",
        "new_value": "USR011",
        "changed_by": "USR001",
        "changed_at": "2026-06-11T08:00:00Z",
      },
      {
        "id": "HIS015",
        "workspace_id": "WS003",
        "task_id": "TASK009",
        "field": "status",
        "old_value": "todo",
        "new_value": "in_progress",
        "changed_by": "USR011",
        "changed_at": "2026-06-12T08:00:00Z",
      },
    ],
  };
}
